### ISSUE TITLE
problema con costruzione dei grafici in determinate condizioni

### ISSUE THREAD

**Issue by Simone-Parrella** [CostaMart/ing-soft2#36]
Traceback (most recent call last):
  File "C:\Users\simon\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\simon\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\simon\Documents\GitHub\ing-soft2\controller\ProjectMetricsContoller.py", line 73, in toRun
    callback(result)
  File "c:\Users\simon\Documents\GitHub\ing-soft2\view\ProjectMetricsPage.py", line 182, in finalize_data_request
    loc, toolbar = graphFactory.makeGraph(master= locFrame, graph= "loc", process_dict = process_dict)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\simon\Documents\GitHub\ing-soft2\view\widgets\GraficiSP\GraphFactory.py", line 38, in makeGraph
    fig = graphProducer(process_dict, fig_loc, ax_loc)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\simon\Documents\GitHub\ing-soft2\view\widgets\GraficiSP\GraphFactory.py", line 65, in _loc
    axloc.set_xlim(left = y2[0], right = y2[right])
                          ~~^^^
IndexError: list index out of range

**Comment by Simone-Parrella** [comment]
L'errore "IndexError: list index out of range" indica che stai cercando di accedere a un indice in una lista che non esiste. In altre parole, stai cercando di accedere a un elemento di una lista utilizzando un indice che è più grande della lunghezza della lista stessa.

Nel tuo caso, l'errore si verifica nella riga:

python
Copy code
axloc.set_xlim(left=y2[0], right=y2[right])
Il problema potrebbe essere dovuto a un valore non valido per l'indice right o a una lista vuota y2. Ecco alcuni suggerimenti per risolvere il problema:

Verifica la lunghezza di y2: Assicurati che y2 sia una lista valida e che abbia almeno due elementi prima di tentare di accedere agli indici 0 e right. Puoi fare ciò stampando la lunghezza della lista prima di utilizzarla:

python
Copy code
print("Lunghezza di y2:", len(y2))
Verifica il valore di right: Assicurati che il valore di right sia un indice valido per la lista y2. Potrebbe essere necessario aggiungere una verifica per garantire che right sia un indice valido prima di utilizzarlo.

python
Copy code
if 0 <= right < len(y2):
    axloc.set_xlim(left=y2[0], right=y2[right])
else:
    print("Valore di 'right' non valido.")
Assicurati che y2 contenga dati: Verifica che y2 contenga dati prima di utilizzare indici. Se y2 è vuota, dovresti gestire questo caso separatamente.

python
Copy code
if y2:
    axloc.set_xlim(left=y2[0], right=y2[right])
else:
    print("La lista 'y2' è vuota.")
Utilizza questi suggerimenti per debuggare e risolvere l'errore "IndexError". Assicurati che la lista sia valida e che l'indice utilizzato sia corretto rispetto alla lunghezza della lista.

**Comment by Simone-Parrella** [comment]
problema non risolto con chatgpt
